spring.application.name=trafo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/sklep_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:shop_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:shop_password}

stripe.stripe_secret_key=${STRIPE_SECRET_KEY:}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvhiw06ts57riz
vqyi5/2cCLg1Kmb1UOgCYZNlxMakMJcqJh8kuFQAO1B54a9PHxv5hM9/QkKmiLml
9k1akSNARKu+xjHWfOYaIe52BIG3DstzmCgRYNnxYN0ZDwnV8seYdpqWrkpyES66
Etcrm06zakYl7l63gY+YcXG8K2Jm7Ef4gQGZLK104qA95bEg23sDodZkuAu6/P75
kDiicF6HEvYCiuJrTazrWVH+97PZOF8vCgIOY8NgLrhrrr3ALG1OyfViiYc6L02z
HxSvl3AJHQOVKCMR2d471Q579WR4q5rwZpn5JfsC0v/zw/piM6LA32O5/EaNp8oT
iL3z1fsfAgMBAAECggEALS/1oYn09m0mz99+wlHHUKxOACHyb6VslXBZahHGse5w
fEFkMyfhOE4M4dPgNhZkNVCjurdsQUNhyAAo2fATizAipvKPUhDFjGS/51Ixstb0
OcYqSo8MjL/LK/BbL+FY0T93fONR9xvFU9IV4vwQvs/VT16Ws9d/CFfsV+0zYBt3
GXTRDlHLspXojyFAsdMld39CwW0eJiqe20pQC8PJF5fs+odtEr0cxheiVW5iVkJ1
TXcU96Ze8LIPDbSBQ92Jif4nJQQqzAVUzGsiGoaYt8uQxKvkZYrn2BAoxsFcczPI
Ga52Qs2BO6IJt+yhNKq0feMJyoKN0LjCXC48HfncAQKBgQDamDKxTcaYnpTjzVCc
Y/pKzloyD4QGzyRNFvtiZmsVyJDQP+t30eJQScVU/Vu6mVWRPy9XtxZqhVAL7pBg
nfsi+L40oHCH31L/eq03/+qYpwUhKLrV3h2ap2PDt/LP73Faejrn7nkHUEvtWaPC
sOZN2D2U+TFzEtrTvhowOKSeXwKBgQDNjzjpbyn3Jx8To4lPMs6gkfInLMi4w2nq
e2MEwP/9rWCyh3ENtQ/YZQ/LSHyo8aQ8wx49W2DpURVM9nL8BTMmiOkkH8Gae0Sv
Dw2+Au8wgPs6qqBjZMkMjDA3mnbRZt9I4ClExsO2BEqKvjO+SdK3OKGw7gC3RM5f
QaMbzwJbQQKBgCHdXFUdkHvKbZSRFUD1OCxopY6F2tVXN+99dPp8lXBtfwnULT2F
1YLMuvZ8vb49zQTQfhwfsChWeN0wW0usjeCQGp96j5RtI6WSss0vJ3/4uBG4BqHl
ZD62Wf1TPRm7pZr3vrJ5vmREq06dCYK69yLuMjQnGuMR87bEB7iavd4PAoGBAI10
cLqa5+sPfeA62qOol+6BYH064UncF8fnbuV3lvHP3MoeUFsZbTUBntPKJxbvapDx
yJ56gn8scBcNRWVOgruS3bUhMU6IY2SAXHmUdVsQd1IQ1txvH7dFxWyOHBPP0fnJ
YDzW9xkLbOx7JQperOWuz/38WnvDmqyMc50QYFPBAoGBALQKd8LQDlscAwIqhEIv
KduvQb1aiyjQt/wCrKKERAL3BRzmh2wiTC8TpNIaKmNOG0p1fs5qUEOmtw7QcH34
f6C0tpYxG3iHcoCHLTJTwGhp+hhtNDZCMxmHwb0iv1mWmbYXXOhmCILQLXFKhUEg
mgJsKDv9QblmzvoJDkQzcOBs