-- Katalog agregatów PRAMAC przygotowany na podstawie kart katalogowych.
-- W środowisku developerskim seed jest odtwarzany przy każdym starcie.
TRUNCATE TABLE product_parameters RESTART IDENTITY CASCADE;
TRUNCATE TABLE product_images RESTART IDENTITY CASCADE;
TRUNCATE TABLE products RESTART IDENTITY CASCADE;

INSERT INTO products (name, price, old_price, stock, description, category, subcategory, sku) VALUES
('Pramac GA10000 — agregat gazowy 10 kVA, 230 V', 0.10, NULL, 2,
 'Stacjonarny, automatyczny agregat gazowy do awaryjnego zasilania domu lub małego obiektu. Obudowa aluminiowa RhinoCoat tłumi hałas i chroni urządzenie przed warunkami atmosferycznymi. Model współpracuje z przełącznikiem zasilania awaryjnego LTS.',
 'Agregaty', 'gazowe', 'PRM-GA10000'),
('Pramac GA13000 — agregat gazowy 13 kVA, 230 V', 21828.46, NULL, 2,
 'Jednofazowy agregat gazowy do automatycznego zasilania awaryjnego. Wyposażony w silnik Generac G-Force, elektroniczny regulator obrotów, sterownik Digital Evolution i łączność Wi-Fi Mobile Link.',
 'Agregaty', 'gazowe', 'PRM-GA13000'),
('Pramac DX8500 PRO+ — agregat diesla 8,5 kW, 400/230 V', 7169.92, NULL, 4,
 'Wytrzymały agregat wysokoprężny serii DX do pracy na budowie, w warsztacie i jako zasilanie rezerwowe. Wersja PRO+ oferuje napięcie trójfazowe i jednofazowe, elektryczny rozruch oraz stabilizację AVR.',
 'Agregaty', 'diesla', 'PRM-DX8500'),
('Pramac P3500i — agregat inwerterowy 3,3 kW, 230 V', 2763.41, NULL, 6,
 'Cichy agregat inwerterowy do zasilania elektroniki, kamperów i urządzeń podczas prac w terenie. Technologia inverter zapewnia stabilne napięcie, a tryb Economy ogranicza zużycie paliwa i hałas.',
 'Agregaty', 'inwerterowe', 'PRM-P3500I'),
('Pramac P3000i — agregat inwerterowy 2,5 kW, 230 V', 2381.30, NULL, 7,
 'Kompaktowy i lekki agregat inwerterowy do zasilania wrażliwej elektroniki. Posiada tryb Economy, zabezpieczenie niskiego poziomu oleju, gniazdo do pracy równoległej oraz dwa porty USB.',
 'Agregaty', 'inwerterowe', 'PRM-P3000I'),
('Pramac E4000 — agregat benzynowy 3,1 kW, 230 V', 2511.38, NULL, 8,
 'Prosty, solidny agregat jednofazowy z ramą rurową do prac remontowych, oświetlenia i zastosowań profesjonalnych. Konstrukcja jest łatwa w obsłudze, transporcie i serwisowaniu.',
 'Agregaty', 'benzynowe', 'PRM-E4000'),
('Pramac MES8000 — agregat benzynowy 7,2 kVA, 230 V', 5446.34, NULL, 4,
 'Profesjonalny agregat z silnikiem Honda, elektrycznym rozruchem i zestawem transportowym. Automatyczny regulator napięcia AVR, zabezpieczenie różnicowe oraz przygotowanie do zdalnego sterowania ułatwiają pracę w wymagających zastosowaniach.',
 'Agregaty', 'benzynowe', 'PRM-MES8000'),
('Pramac WX6250 ES — agregat AVR 5,5 kW, 400/230 V', 2600.81, NULL, 5,
 'Trójfazowy agregat benzynowy z AVR, elektrycznym i ręcznym rozruchem oraz zintegrowanym zestawem jezdnym. Duży zbiornik i cyfrowy multimetr sprawdzają się podczas długiej pracy na budowie.',
 'Agregaty', 'benzynowe', 'PRM-WX6250ES'),
('Pramac WX7000 — agregat AVR 6,1 kW, 230 V', 2706.50, NULL, 5,
 'Jednofazowy agregat benzynowy do prac terenowych i awaryjnego zasilania. Wyposażony w AVR, elektryczny i ręczny rozruch, składane uchwyty, koła transportowe oraz wielofunkcyjny wyświetlacz.',
 'Agregaty', 'benzynowe', 'PRM-WX7000'),
('Pramac PMi 4500 — agregat inwerterowy 4,2 kW, 230 V', 2722.76, NULL, 5,
 'Wyciszony agregat inwerterowy do elektroniki, domu i zastosowań terenowych. Automatyczny tryb Economy dopasowuje obroty do obciążenia, a stabilne napięcie z falownika chroni czułe odbiorniki.',
 'Agregaty', 'inwerterowe', 'PRM-PMI4500'),
('Pramac S12000 — agregat AVR 13,9 kVA, 400/230 V', 15340.65, NULL, 3,
 'Profesjonalny agregat serii S do intensywnej pracy. Wersja 400/230 V z AVR, złączem CONN i zabezpieczeniem różnicowym DPP oferuje moc trójfazową oraz możliwość zasilania odbiorników jednofazowych.',
 'Agregaty', 'benzynowe', 'PRM-S12000-400'),
('Pramac GA20000 — agregat gazowy 20/17 kVA, 400 V', 24389.43, NULL, 1,
 'Trójfazowy agregat gazowy do automatycznego zasilania awaryjnego większych obiektów. Cicha obudowa aluminiowa, sterownik Digital Evolution, AVR, Wi-Fi Mobile Link oraz kompatybilność z przełącznikiem LTS tworzą kompletny system rezerwowy.',
 'Agregaty', 'gazowe', 'PRM-GA20000'),
-- Agregaty CGM Italia — stan magazynowy od producenta (ceny prowizoryczne, podwyższone do czasu ustalenia finalnej cennika).
('CGM Super Power 4000IE — agregat inwerterowy 3,6 kW, 230 V', 6499.00, NULL, 3,
 'Włoski agregat inwerterowy CGM Italia z generatorem PMG i czystym napięciem — bezpieczny dla elektroniki wrażliwej, pieców i kotłów. Wyciszona obudowa 62 dB(A), rozruch elektryczny z pilotem zdalnego sterowania, panel z multimetrem i licznikiem motogodzin, gniazda USB oraz wózek transportowy.',
 'Agregaty', 'inwerterowe', 'CGM-4000IE'),
('CGM Super Power 6000SP — agregat benzynowy 5,4 kW, 230 V', 4299.00, NULL, 11,
 'Jednofazowy agregat benzynowy CGM Italia do domu, warsztatu i pracy w terenie. Stabilizacja napięcia AVR, duży zbiornik 25 l i ramowa konstrukcja zapewniają do ok. 13,8 h pracy bez dostępu do sieci.',
 'Agregaty', 'benzynowe', 'CGM-6000SP'),
('CGM Super Power 9000SPE — agregat benzynowy 7,2 kW, 230 V', 5799.00, NULL, 6,
 'Mocny agregat jednofazowy CGM Italia z silnikiem 16 HP i rozruchem elektrycznym 12 V. Regulacja AVR ±1 %, zbiornik 25 l, gniazda Schuko 230 V i CEE 32 A oraz wózek transportowy — do awaryjnego zasilania domu i instalacji mobilnych.',
 'Agregaty', 'benzynowe', 'CGM-9000SPE'),
('CGM Super Power 9000SPTE — agregat benzynowy 9 kVA / 7,2 kW, 400 V', 6299.00, NULL, 5,
 'Trójfazowy agregat 400 V włoskiego producenta CGM Italia. Silnik 16 HP, rozruch elektryczny 12 V i regulacja AVR ±1 %; zbiornik 25 l, gniazdo CEE 16 A 400 V i wózek transportowy — do awaryjnego zasilania instalacji trójfazowych.',
 'Agregaty', 'benzynowe', 'CGM-9000SPTE'),
('CGM C13000HTE — agregat benzynowy 12 kVA / 13,2 kVA, 230/400 V', 17999.00, NULL, 1,
 'Trójfazowy agregat CGM Italia z silnikiem Honda GX630, rozruchem elektrycznym i regulacją AVR. Moc ciągła 12 kVA (szczyt 13,2 kVA), gniazda CEE 32 A 400 V i CEE 16 A 230 V — solidne zasilanie awaryjne domu i obiektu.',
 'Agregaty', 'benzynowe', 'CGM-C13000HTE'),
('Pramac PMi 6500 — agregat inwerterowy 6,0 kW, 230 V', 3982.93, NULL, 5,
 'Wyciszony agregat inwerterowy o mocy 6,0 kW do zasilania wrażliwej elektroniki i urządzeń domowych. Posiada rozruch elektryczny, złącze ATS, możliwość sterowania pilotem oraz inteligentny tryb Economy, który dostosowuje obroty do obciążenia, oszczędzając paliwo.',
 'Agregaty', 'inwerterowe', 'PRM-PMI6500');

-- Zdjęcia produktów są wyłącznie w Supabase (product_images/products/{id}.jpg).
-- Nie seedujemy lokalnych miniatur /products/pramac-* — słaba jakość, dublowały galerię.

INSERT INTO product_parameters (product_id, parameter_key, parameter_value) VALUES
(1, 'moc_maksymalna', '10 000 VA'),
(1, 'napiecie', '230 V'),
(1, 'liczba_faz', '1'),
(1, 'czestotliwosc', '50 Hz'),
(1, 'rodzaj_paliwa', 'Gaz ziemny lub LPG'),
(1, 'silnik', 'Generac G-Force OHV, 999 cm³'),
(1, 'rozruch', 'Elektryczny, automatyczny'),
(1, 'regulacja_napiecia', 'True Power / AVR'),
(1, 'poziom_halasu', '54 dB(A) w trybie Quiet-Test'),
(1, 'wymiary', '1232 × 648 × 733 mm'),
(1, 'waga', '176 kg'),
(1, 'gwarancja', '5 lat producenta'),
(2, 'moc_maksymalna', '13 000 VA'),
(2, 'napiecie', '230 V'),
(2, 'liczba_faz', '1'),
(2, 'czestotliwosc', '50 Hz'),
(2, 'rodzaj_paliwa', 'Gaz ziemny lub LPG'),
(2, 'silnik', 'Generac G-Force OHV, 999 cm³'),
(2, 'rozruch', 'Elektryczny, automatyczny'),
(2, 'regulacja_napiecia', 'True Power / AVR'),
(2, 'poziom_halasu', '54 dB(A) w trybie Quiet-Test'),
(2, 'wymiary', '1232 × 648 × 733 mm'),
(2, 'waga', '193 kg'),
(2, 'gwarancja', '5 lat producenta'),
(3, 'moc_maksymalna', '8500 W'),
(3, 'moc_znamionowa', '8000 W'),
(3, 'napiecie', '400/230 V'),
(3, 'liczba_faz', '3 / 1'),
(3, 'czestotliwosc', '50 Hz'),
(3, 'rodzaj_paliwa', 'Olej napędowy'),
(3, 'silnik', 'Pramac, Stage V'),
(3, 'rozruch', 'Elektryczny'),
(3, 'regulacja_napiecia', 'AVR'),
(3, 'zastosowanie', 'Praca ciężka / budowa'),
(3, 'wyposazenie', 'Gniazda: 1x SCHUKO 230V 16A, 1x CEE 230V 16A, 1x CEE 400V 16A. Ochrona: RCD, magnetyczno-termiczna. Sterowanie: złącze ATS, 2-przewodowe podłączanie, pilot, przełącznik mono/trójfazowy (FULL POWER). Inne: podgrzewacz wstępny, multimetr cyfrowy.'),
(4, 'moc_maksymalna', '3300 W'),
(4, 'moc_znamionowa', '3000 W'),
(4, 'napiecie', '230 V'),
(4, 'liczba_faz', '1'),
(4, 'czestotliwosc', '50 Hz'),
(4, 'rodzaj_paliwa', 'Benzyna'),
(4, 'silnik', 'Pramac OHV, Stage V, 212 cm³'),
(4, 'rozruch', 'Elektryczny + ręczny'),
(4, 'regulacja_napiecia', 'Inverter'),
(4, 'zbiornik_paliwa', '10 l'),
(4, 'poziom_halasu', '61 dB(A) w odległości 7 m'),
(4, 'waga', '49,5 kg'),
(5, 'moc_maksymalna', '2500 W'),
(5, 'moc_znamionowa', '2300 W'),
(5, 'napiecie', '230 V'),
(5, 'liczba_faz', '1'),
(5, 'czestotliwosc', '50 Hz'),
(5, 'rodzaj_paliwa', 'Benzyna'),
(5, 'silnik', 'Pramac OHV, Stage V'),
(5, 'rozruch', 'Ręczny'),
(5, 'regulacja_napiecia', 'Inverter'),
(5, 'zbiornik_paliwa', '4 l'),
(5, 'czas_pracy', '3,5 h przy 75% obciążenia'),
(5, 'poziom_halasu', '61 dB(A) w odległości 7 m'),
(5, 'waga', '27 kg'),
(6, 'moc_maksymalna', '3400 VA / 3100 W'),
(6, 'moc_znamionowa', '2900 VA / 2600 W'),
(6, 'napiecie', '230 V'),
(6, 'liczba_faz', '1'),
(6, 'czestotliwosc', '50 Hz'),
(6, 'rodzaj_paliwa', 'Benzyna'),
(6, 'silnik', 'Honda, 3000 obr./min'),
(6, 'rozruch', 'Ręczny'),
(6, 'regulacja_napiecia', 'Kondensator'),
(6, 'zbiornik_paliwa', '3,1 l'),
(6, 'czas_pracy', '2,65 h przy 75% obciążenia'),
(6, 'poziom_halasu', '68 dB(A) w odległości 7 m'),
(6, 'waga', '36 kg'),
(7, 'moc_maksymalna', '7,2 kVA / 6,4 kW'),
(7, 'moc_ciagla', '6,0 kVA / 5,4 kW'),
(7, 'napiecie', '230 V'),
(7, 'liczba_faz', '1'),
(7, 'czestotliwosc', '50 Hz'),
(7, 'rodzaj_paliwa', 'Benzyna'),
(7, 'silnik', 'Honda'),
(7, 'rozruch', 'Elektryczny + ręczny'),
(7, 'regulacja_napiecia', 'AVR'),
(7, 'wyposazenie', 'Zestaw transportowy, DPP, przygotowanie AMF/RSS'),
(8, 'moc_maksymalna', '6100 W'),
(8, 'moc_znamionowa', '5500 W'),
(8, 'napiecie', '400/230 V'),
(8, 'liczba_faz', '3'),
(8, 'czestotliwosc', '50 Hz'),
(8, 'rodzaj_paliwa', 'Benzyna'),
(8, 'silnik', 'Pramac OHV, Stage V'),
(8, 'rozruch', 'Elektryczny + ręczny'),
(8, 'regulacja_napiecia', 'AVR'),
(8, 'zbiornik_paliwa', '26 l'),
(8, 'czas_pracy', '12 h przy 50% obciążenia'),
(8, 'poziom_halasu', '69 dB(A) w odległości 7 m'),
(8, 'waga', '90 kg'),
(9, 'moc_maksymalna', '6100 W'),
(9, 'moc_znamionowa', '5800 W'),
(9, 'napiecie', '230 V'),
(9, 'liczba_faz', '1'),
(9, 'czestotliwosc', '50 Hz'),
(9, 'rodzaj_paliwa', 'Benzyna'),
(9, 'silnik', 'Pramac OHV, Stage V'),
(9, 'rozruch', 'Elektryczny + ręczny'),
(9, 'regulacja_napiecia', 'AVR'),
(9, 'zbiornik_paliwa', '26 l'),
(9, 'czas_pracy', '11,3 h przy 50% obciążenia'),
(9, 'poziom_halasu', '69 dB(A) w odległości 7 m'),
(9, 'waga', '90 kg'),
(10, 'moc_maksymalna', '4200 W'),
(10, 'moc_znamionowa', '3800 W'),
(10, 'napiecie', '230 V'),
(10, 'liczba_faz', '1'),
(10, 'czestotliwosc', '50 Hz'),
(10, 'rodzaj_paliwa', 'Benzyna'),
(10, 'silnik', 'Pramac OHV, Stage V'),
(10, 'rozruch', 'Elektryczny + ręczny'),
(10, 'regulacja_napiecia', 'Inverter'),
(10, 'zbiornik_paliwa', '12 l'),
(10, 'czas_pracy', '9,7 h przy 50% obciążenia w trybie Eco'),
(10, 'poziom_halasu', '68 dB(A) w odległości 7 m'),
(10, 'waga', '42,5 kg'),
(11, 'moc_maksymalna', '13,9 kVA / 11,1 kW'),
(11, 'moc_ciagla', '11,8 kVA / 9,5 kW'),
(11, 'moc_jednofazowa', '5,6 kVA'),
(11, 'napiecie', '400/230 V'),
(11, 'liczba_faz', '3'),
(11, 'czestotliwosc', '50 Hz'),
(11, 'rodzaj_paliwa', 'Benzyna'),
(11, 'silnik', 'Honda'),
(11, 'rozruch', 'Elektryczny'),
(11, 'regulacja_napiecia', 'AVR'),
(11, 'wyposazenie', 'CONN, DPP, przygotowanie AMF/RSS, zestaw transportowy'),
(12, 'moc_maksymalna', '20 000 VA LPG / 17 000 VA gaz ziemny'),
(12, 'napiecie', '400 V'),
(12, 'liczba_faz', '3'),
(12, 'czestotliwosc', '50 Hz'),
(12, 'wspolczynnik_mocy', 'cos φ 0,8'),
(12, 'rodzaj_paliwa', 'Gaz ziemny lub LPG'),
(12, 'silnik', 'Generac G-Force OHV, 999 cm³, 2 cylindry V'),
(12, 'rozruch', 'Elektryczny, automatyczny'),
(12, 'regulacja_napiecia', 'AVR'),
(12, 'poziom_halasu', '59 dB(A) w trybie Quiet-Test'),
(12, 'wymiary', '1232 × 648 × 733 mm'),
(12, 'waga', '220 kg'),
(12, 'gwarancja', '5 lat producenta'),
(13, 'moc_maksymalna', '4 000 VA / 3 600 W'),
(13, 'napiecie', '230 V'),
(13, 'liczba_faz', '1'),
(13, 'czestotliwosc', '50 Hz'),
(13, 'wspolczynnik_mocy', 'cos φ 0,9'),
(13, 'rodzaj_paliwa', 'Benzyna'),
(13, 'silnik', 'CGM, 8 HP, Stage V, zmienna prędkość'),
(13, 'rozruch', 'Elektryczny + pilot zdalnego sterowania'),
(13, 'regulacja_napiecia', 'Inwerter / AVR ±1 %'),
(13, 'przebieg_napiecia', 'Czysta sinusoida (PMG)'),
(13, 'zbiornik_paliwa', '7,8 l'),
(13, 'czas_pracy', 'do 7,1 h przy 50 % obciążenia'),
(13, 'poziom_halasu', '62 dB(A)'),
(13, 'wymiary', '590 × 300 × 560 mm'),
(13, 'waga', '38,5 kg'),
(13, 'wyposazenie', 'Obudowa wyciszona, 2 × Schuko 230 V, 12 V DC, 2 × USB, wózek transportowy'),
(14, 'moc_maksymalna', '5 400 VA / 5 400 W'),
(14, 'moc_znamionowa', '5 000 VA / 5 000 W'),
(14, 'napiecie', '230 V'),
(14, 'liczba_faz', '1'),
(14, 'czestotliwosc', '50 Hz'),
(14, 'rodzaj_paliwa', 'Benzyna'),
(14, 'silnik', 'CGM, 4-suwowy, Stage V'),
(14, 'rozruch', 'Ręczny'),
(14, 'regulacja_napiecia', 'AVR'),
(14, 'zbiornik_paliwa', '25 l'),
(14, 'czas_pracy', 'ok. 13,8 h'),
(14, 'wymiary', '717 × 545 × 592 mm'),
(14, 'waga', 'ok. 67 kg'),
(15, 'moc_maksymalna', '9 000 VA / 7 200 W'),
(15, 'napiecie', '230 V'),
(15, 'liczba_faz', '1'),
(15, 'czestotliwosc', '50 Hz'),
(15, 'wspolczynnik_mocy', 'cos φ 0,8'),
(15, 'prad_znamionowy', '37 A'),
(15, 'rodzaj_paliwa', 'Benzyna'),
(15, 'silnik', 'CGM, 16 HP (11,7 kW), 460 cm³, Stage V'),
(15, 'rozruch', 'Elektryczny (12 V) + ręczny'),
(15, 'regulacja_napiecia', 'AVR ±1 %'),
(15, 'zbiornik_paliwa', '25 l'),
(15, 'czas_pracy', 'do 11,9 h przy 75 % obciążenia'),
(15, 'wymiary', '725 × 600 × 620 mm'),
(15, 'waga', '87 kg'),
(15, 'wyposazenie', 'Gniazdo Schuko 230 V, CEE 32 A 230 V, 12 V DC, wózek transportowy'),
(16, 'moc_maksymalna', '9 000 VA / 7 200 W'),
(16, 'napiecie', '400 V'),
(16, 'liczba_faz', '3'),
(16, 'czestotliwosc', '50 Hz'),
(16, 'wspolczynnik_mocy', 'cos φ 0,8'),
(16, 'prad_znamionowy', '13 A'),
(16, 'rodzaj_paliwa', 'Benzyna'),
(16, 'silnik', 'CGM, 16 HP (11,7 kW), 460 cm³, Stage V'),
(16, 'rozruch', 'Elektryczny (12 V)'),
(16, 'regulacja_napiecia', 'AVR ±1 %'),
(16, 'zbiornik_paliwa', '25 l'),
(16, 'czas_pracy', 'do 11,9 h przy 75 % obciążenia'),
(16, 'wymiary', '725 × 600 × 620 mm'),
(16, 'waga', '87 kg'),
(16, 'wyposazenie', 'Gniazdo Schuko 230 V, CEE 16 A 5P 400 V, 12 V DC, wózek transportowy'),
(17, 'moc_maksymalna', '13 200 VA / 10 500 W'),
(17, 'moc_znamionowa', '12 000 VA / 9 600 W'),
(17, 'napiecie', '230/400 V'),
(17, 'liczba_faz', '3'),
(17, 'czestotliwosc', '50 Hz'),
(17, 'rodzaj_paliwa', 'Benzyna'),
(17, 'silnik', 'Honda GX630, Stage V'),
(17, 'rozruch', 'Elektryczny'),
(17, 'regulacja_napiecia', 'AVR'),
(17, 'zbiornik_paliwa', '15 l'),
(17, 'czas_pracy', '3,1 h przy 75 % obciążenia'),
(17, 'wyposazenie', '1 × CEE 32 A 5P 400 V, 1 × CEE 16 A 3P 230 V'),
(18, 'moc_maksymalna', '6500 W'),
(18, 'moc_znamionowa', '6000 W'),
(18, 'napiecie', '230 V'),
(18, 'liczba_faz', '1'),
(18, 'czestotliwosc', '50 Hz'),
(18, 'rodzaj_paliwa', 'Benzyna'),
(18, 'silnik', 'Pramac OHV, Stage V'),
(18, 'rozruch', 'Elektryczny + ręczny (złącze ATS, pilot)'),
(18, 'regulacja_napiecia', 'Inverter'),
(18, 'zbiornik_paliwa', '14 l'),
(18, 'czas_pracy', '6,6 h przy 50% obciążenia w trybie Eco'),
(18, 'poziom_halasu', '68 dB(A) w odległości 7 m'),
(18, 'wymiary', '625 × 448 × 560 mm'),
(18, 'waga', '50,5 kg'),
(18, 'wyposazenie', 'Gniazda: 1x SCHUKO 230V 16A, 1x CEE 230V 32A, wyjście DC 12V 6A. Ochrona: termiczna, przeciążeniowa, czujnik oleju. Sterowanie: ATS, 2-przewodowe podłączanie, pilot, wskaźnik poziomu paliwa i multimetr cyfrowy.');
