-- Katalog agregatów PRAMAC przygotowany na podstawie kart katalogowych.
-- W środowisku developerskim seed jest odtwarzany przy każdym starcie.
TRUNCATE TABLE product_parameters RESTART IDENTITY CASCADE;
TRUNCATE TABLE product_images RESTART IDENTITY CASCADE;
TRUNCATE TABLE products RESTART IDENTITY CASCADE;

INSERT INTO products (name, price, old_price, stock, description, category, sku) VALUES
('Pramac GA10000 — agregat gazowy 10 kVA, 230 V', 34500.00, NULL, 2,
 'Stacjonarny, automatyczny agregat gazowy do awaryjnego zasilania domu lub małego obiektu. Obudowa aluminiowa RhinoCoat tłumi hałas i chroni urządzenie przed warunkami atmosferycznymi. Model współpracuje z przełącznikiem zasilania awaryjnego LTS.',
 'Agregaty', 'PRM-GA10000'),
('Pramac GA13000 — agregat gazowy 13 kVA, 230 V', 38900.00, NULL, 2,
 'Jednofazowy agregat gazowy do automatycznego zasilania awaryjnego. Wyposażony w silnik Generac G-Force, elektroniczny regulator obrotów, sterownik Digital Evolution i łączność Wi-Fi Mobile Link.',
 'Agregaty', 'PRM-GA13000'),
('Pramac DX8500 PRO+ — agregat diesla 8,5 kW, 400/230 V', 12900.00, NULL, 4,
 'Wytrzymały agregat wysokoprężny serii DX do pracy na budowie, w warsztacie i jako zasilanie rezerwowe. Wersja PRO+ oferuje napięcie trójfazowe i jednofazowe, elektryczny rozruch oraz stabilizację AVR.',
 'Agregaty', 'PRM-DX8500'),
('Pramac P3500i — agregat inwerterowy 3,3 kW, 230 V', 3200.00, NULL, 6,
 'Cichy agregat inwerterowy do zasilania elektroniki, kamperów i urządzeń podczas prac w terenie. Technologia inverter zapewnia stabilne napięcie, a tryb Economy ogranicza zużycie paliwa i hałas.',
 'Agregaty', 'PRM-P3500I'),
('Pramac P3000i — agregat inwerterowy 2,5 kW, 230 V', 2400.00, NULL, 7,
 'Kompaktowy i lekki agregat inwerterowy do zasilania wrażliwej elektroniki. Posiada tryb Economy, zabezpieczenie niskiego poziomu oleju, gniazdo do pracy równoległej oraz dwa porty USB.',
 'Agregaty', 'PRM-P3000I'),
('Pramac E4000 — agregat benzynowy 3,1 kW, 230 V', 2200.00, NULL, 8,
 'Prosty, solidny agregat jednofazowy z ramą rurową do prac remontowych, oświetlenia i zastosowań profesjonalnych. Konstrukcja jest łatwa w obsłudze, transporcie i serwisowaniu.',
 'Agregaty', 'PRM-E4000'),
('Pramac MES8000 — agregat benzynowy 7,2 kVA, 230 V', 6200.00, NULL, 4,
 'Profesjonalny agregat z silnikiem Honda, elektrycznym rozruchem i zestawem transportowym. Automatyczny regulator napięcia AVR, zabezpieczenie różnicowe oraz przygotowanie do zdalnego sterowania ułatwiają pracę w wymagających zastosowaniach.',
 'Agregaty', 'PRM-MES8000'),
('Pramac WX6250 ES — agregat AVR 5,5 kW, 400/230 V', 6200.00, NULL, 5,
 'Trójfazowy agregat benzynowy z AVR, elektrycznym i ręcznym rozruchem oraz zintegrowanym zestawem jezdnym. Duży zbiornik i cyfrowy multimetr sprawdzają się podczas długiej pracy na budowie.',
 'Agregaty', 'PRM-WX6250ES'),
('Pramac WX7000 — agregat AVR 6,1 kW, 230 V', 5900.00, NULL, 5,
 'Jednofazowy agregat benzynowy do prac terenowych i awaryjnego zasilania. Wyposażony w AVR, elektryczny i ręczny rozruch, składane uchwyty, koła transportowe oraz wielofunkcyjny wyświetlacz.',
 'Agregaty', 'PRM-WX7000'),
('Pramac PMi 4500 — agregat inwerterowy 4,2 kW, 230 V', 4100.00, NULL, 5,
 'Wyciszony agregat inwerterowy do elektroniki, domu i zastosowań terenowych. Automatyczny tryb Economy dopasowuje obroty do obciążenia, a stabilne napięcie z falownika chroni czułe odbiorniki.',
 'Agregaty', 'PRM-PMI4500'),
('Pramac S12000 — agregat AVR 13,9 kVA, 400/230 V', 12500.00, NULL, 3,
 'Profesjonalny agregat serii S do intensywnej pracy. Wersja 400/230 V z AVR, złączem CONN i zabezpieczeniem różnicowym DPP oferuje moc trójfazową oraz możliwość zasilania odbiorników jednofazowych.',
 'Agregaty', 'PRM-S12000-400'),
('Pramac GA20000 — agregat gazowy 20/17 kVA, 400 V', 49900.00, NULL, 1,
 'Trójfazowy agregat gazowy do automatycznego zasilania awaryjnego większych obiektów. Cicha obudowa aluminiowa, sterownik Digital Evolution, AVR, Wi-Fi Mobile Link oraz kompatybilność z przełącznikiem LTS tworzą kompletny system rezerwowy.',
 'Agregaty', 'PRM-GA20000');

INSERT INTO product_images (product_id, image_url) VALUES
(1, '/products/pramac-ga10000.webp'),
(2, '/products/pramac-ga13000.jpg'),
(3, '/products/pramac-dx8500.webp'),
(4, '/products/pramac-p3500i.jpg'),
(5, '/products/pramac-p3000i.jpg'),
(6, '/products/pramac-e4000.jpg'),
(7, '/products/pramac-mes8000.jpg'),
(8, '/products/pramac-wx6250-es.jpg'),
(9, '/products/pramac-wx7000.jpg'),
(10, '/products/pramac-pmi4500.webp'),
(11, '/products/pramac-s12000.jpg'),
(12, '/products/pramac-ga20000.png');

INSERT INTO product_parameters (product_id, parameter_key, parameter_value) VALUES
(1, 'moc_maksymalna', '10 000 VA'),
(1, 'napiecie', '230 V'),
(1, 'liczba_faz', '1'),
(1, 'czestotliwosc', '50 Hz'),
(1, 'rodzaj_paliwa', 'Gaz ziemny lub LPG'),
(1, 'silnik', 'Generac G-Force OHV, 999 cm³'),
(1, 'rozruch', 'Elektryczny, automatyczny'),
(1, 'regulacja_napiecia', 'True Power / AVR'),
(1, 'poziom_halasu', '54 dB(A) w trybie Quiet-Test'),
(1, 'wymiary', '1232 × 648 × 733 mm'),
(1, 'waga', '176 kg'),
(1, 'gwarancja', '5 lat producenta'),
(2, 'moc_maksymalna', '13 000 VA'),
(2, 'napiecie', '230 V'),
(2, 'liczba_faz', '1'),
(2, 'czestotliwosc', '50 Hz'),
(2, 'rodzaj_paliwa', 'Gaz ziemny lub LPG'),
(2, 'silnik', 'Generac G-Force OHV, 999 cm³'),
(2, 'rozruch', 'Elektryczny, automatyczny'),
(2, 'regulacja_napiecia', 'True Power / AVR'),
(2, 'poziom_halasu', '54 dB(A) w trybie Quiet-Test'),
(2, 'wymiary', '1232 × 648 × 733 mm'),
(2, 'waga', '193 kg'),
(2, 'gwarancja', '5 lat producenta'),
(3, 'moc_maksymalna', '8500 W'),
(3, 'moc_znamionowa', '8000 W'),
(3, 'napiecie', '400/230 V'),
(3, 'liczba_faz', '3 / 1'),
(3, 'czestotliwosc', '50 Hz'),
(3, 'rodzaj_paliwa', 'Olej napędowy'),
(3, 'silnik', 'Pramac, Stage V'),
(3, 'rozruch', 'Elektryczny'),
(3, 'regulacja_napiecia', 'AVR'),
(3, 'zastosowanie', 'Praca ciężka / budowa'),
(4, 'moc_maksymalna', '3300 W'),
(4, 'moc_znamionowa', '3000 W'),
(4, 'napiecie', '230 V'),
(4, 'liczba_faz', '1'),
(4, 'czestotliwosc', '50 Hz'),
(4, 'rodzaj_paliwa', 'Benzyna'),
(4, 'silnik', 'Pramac OHV, Stage V, 212 cm³'),
(4, 'rozruch', 'Elektryczny + ręczny'),
(4, 'regulacja_napiecia', 'Inverter'),
(4, 'zbiornik_paliwa', '10 l'),
(4, 'poziom_halasu', '61 dB(A) w odległości 7 m'),
(4, 'waga', '49,5 kg'),
(5, 'moc_maksymalna', '2500 W'),
(5, 'moc_znamionowa', '2300 W'),
(5, 'napiecie', '230 V'),
(5, 'liczba_faz', '1'),
(5, 'czestotliwosc', '50 Hz'),
(5, 'rodzaj_paliwa', 'Benzyna'),
(5, 'silnik', 'Pramac OHV, Stage V'),
(5, 'rozruch', 'Ręczny'),
(5, 'regulacja_napiecia', 'Inverter'),
(5, 'zbiornik_paliwa', '4 l'),
(5, 'czas_pracy', '3,5 h przy 75% obciążenia'),
(5, 'poziom_halasu', '61 dB(A) w odległości 7 m'),
(5, 'waga', '27 kg'),
(6, 'moc_maksymalna', '3400 VA / 3100 W'),
(6, 'moc_znamionowa', '2900 VA / 2600 W'),
(6, 'napiecie', '230 V'),
(6, 'liczba_faz', '1'),
(6, 'czestotliwosc', '50 Hz'),
(6, 'rodzaj_paliwa', 'Benzyna'),
(6, 'silnik', 'Honda, 3000 obr./min'),
(6, 'rozruch', 'Ręczny'),
(6, 'regulacja_napiecia', 'Kondensator'),
(6, 'zbiornik_paliwa', '3,1 l'),
(6, 'czas_pracy', '2,65 h przy 75% obciążenia'),
(6, 'poziom_halasu', '68 dB(A) w odległości 7 m'),
(6, 'waga', '36 kg'),
(7, 'moc_maksymalna', '7,2 kVA / 6,4 kW'),
(7, 'moc_ciagla', '6,0 kVA / 5,4 kW'),
(7, 'napiecie', '230 V'),
(7, 'liczba_faz', '1'),
(7, 'czestotliwosc', '50 Hz'),
(7, 'rodzaj_paliwa', 'Benzyna'),
(7, 'silnik', 'Honda'),
(7, 'rozruch', 'Elektryczny + ręczny'),
(7, 'regulacja_napiecia', 'AVR'),
(7, 'wyposazenie', 'Zestaw transportowy, DPP, przygotowanie AMF/RSS'),
(8, 'moc_maksymalna', '6100 W'),
(8, 'moc_znamionowa', '5500 W'),
(8, 'napiecie', '400/230 V'),
(8, 'liczba_faz', '3'),
(8, 'czestotliwosc', '50 Hz'),
(8, 'rodzaj_paliwa', 'Benzyna'),
(8, 'silnik', 'Pramac OHV, Stage V'),
(8, 'rozruch', 'Elektryczny + ręczny'),
(8, 'regulacja_napiecia', 'AVR'),
(8, 'zbiornik_paliwa', '26 l'),
(8, 'czas_pracy', '12 h przy 50% obciążenia'),
(8, 'poziom_halasu', '69 dB(A) w odległości 7 m'),
(8, 'waga', '90 kg'),
(9, 'moc_maksymalna', '6100 W'),
(9, 'moc_znamionowa', '5800 W'),
(9, 'napiecie', '230 V'),
(9, 'liczba_faz', '1'),
(9, 'czestotliwosc', '50 Hz'),
(9, 'rodzaj_paliwa', 'Benzyna'),
(9, 'silnik', 'Pramac OHV, Stage V'),
(9, 'rozruch', 'Elektryczny + ręczny'),
(9, 'regulacja_napiecia', 'AVR'),
(9, 'zbiornik_paliwa', '26 l'),
(9, 'czas_pracy', '11,3 h przy 50% obciążenia'),
(9, 'poziom_halasu', '69 dB(A) w odległości 7 m'),
(9, 'waga', '90 kg'),
(10, 'moc_maksymalna', '4200 W'),
(10, 'moc_znamionowa', '3800 W'),
(10, 'napiecie', '230 V'),
(10, 'liczba_faz', '1'),
(10, 'czestotliwosc', '50 Hz'),
(10, 'rodzaj_paliwa', 'Benzyna'),
(10, 'silnik', 'Pramac OHV, Stage V'),
(10, 'rozruch', 'Elektryczny + ręczny'),
(10, 'regulacja_napiecia', 'Inverter'),
(10, 'zbiornik_paliwa', '12 l'),
(10, 'czas_pracy', '9,7 h przy 50% obciążenia w trybie Eco'),
(10, 'poziom_halasu', '68 dB(A) w odległości 7 m'),
(10, 'waga', '42,5 kg'),
(11, 'moc_maksymalna', '13,9 kVA / 11,1 kW'),
(11, 'moc_ciagla', '11,8 kVA / 9,5 kW'),
(11, 'moc_jednofazowa', '5,6 kVA'),
(11, 'napiecie', '400/230 V'),
(11, 'liczba_faz', '3'),
(11, 'czestotliwosc', '50 Hz'),
(11, 'rodzaj_paliwa', 'Benzyna'),
(11, 'silnik', 'Honda'),
(11, 'rozruch', 'Elektryczny'),
(11, 'regulacja_napiecia', 'AVR'),
(11, 'wyposazenie', 'CONN, DPP, przygotowanie AMF/RSS, zestaw transportowy'),
(12, 'moc_maksymalna', '20 000 VA LPG / 17 000 VA gaz ziemny'),
(12, 'napiecie', '400 V'),
(12, 'liczba_faz', '3'),
(12, 'czestotliwosc', '50 Hz'),
(12, 'wspolczynnik_mocy', 'cos φ 0,8'),
(12, 'rodzaj_paliwa', 'Gaz ziemny lub LPG'),
(12, 'silnik', 'Generac G-Force OHV, 999 cm³, 2 cylindry V'),
(12, 'rozruch', 'Elektryczny, automatyczny'),
(12, 'regulacja_napiecia', 'AVR'),
(12, 'poziom_halasu', '59 dB(A) w trybie Quiet-Test'),
(12, 'wymiary', '1232 × 648 × 733 mm'),
(12, 'waga', '220 kg'),
(12, 'gwarancja', '5 lat producenta');
